package anypoint

import (
	"context"
	"errors"
	"fmt"
	"io/ioutil"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	connApp "github.com/mulesoft-consulting/anypoint-client-go/connected_app"
)

func dataSourceConnectedApp() *schema.Resource {
	return &schema.Resource{
		ReadContext: dataSourceConnectedAppRead,
		Description: `
		Reads all ` + "`" + `connected apps` + "`" + ` in your organization.
		`,
		Schema: map[string]*schema.Schema{
			"id": {
				Type:        schema.TypeString,
				Required:    true,
				Description: "The unique id of this connected app generated by the anypoint platform.",
			},
			"name": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The name of the connected app.",
			},
			"secret": {
				Type:        schema.TypeString,
				Computed:    true,
				Sensitive:   true,
				Description: "The secret of the connected app.",
			},
			"user_id": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The id of the user who owns the connected app",
			},
			"organization_id": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The organization id where the connected app's owner is defined.",
			},
			"grant_types": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
				Description: `
				List of grant types. For "on its own behalf" connected apps the only allowed value is "client_credentials". 
				The allowed values for "on behalf of user" connected apps are: "authorization_code", "refresh_token",
				"password", and "urn:ietf:params:oauth:grant-type:jwt-bearer".
				`,
			},
			"redirect_uris": {
				Description: "Configure which URIs users may be directed to after authorization",
				Type:        schema.TypeList,
				Computed:    true,
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},
			"scope": {
				Description: "The scopes this connected app has authorization to work on",
				Type:        schema.TypeList,
				Computed:    true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"scope": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "Scope",
						},
						"org_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "The id of the business group the scope is valid. Only required for particular scopes",
						},
						"env_id": {
							Type:        schema.TypeString,
							Computed:    true,
							Description: "The id of the environment the scope is valid. Only required for particular scopes",
						},
					},
				},
			},
			"public_keys": {
				Type:     schema.TypeList,
				Computed: true,
				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
				Description: `
				Application public key (PEM format). Used to validate JWT authorization grants.
				Required when grant type jwt-bearer is selected.
				`,
			},
			"client_uri": {
				Type:     schema.TypeString,
				Computed: true,
				Description: `
				Users can visit this URL to learn more about your app. Required for "on behalf of user" 
				connected apps
				`,
			},
			"enabled": {
				Type:        schema.TypeBool,
				Computed:    true,
				Description: "True if the connected app is enabled",
			},
			"audience": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Who can use this application",
			},
			"policy_uri": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"tos_uri": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"cert_expiry": {
				Type:     schema.TypeString,
				Computed: true,
			},
		},
	}
}

func dataSourceConnectedAppRead(ctx context.Context, d *schema.ResourceData, m interface{}) diag.Diagnostics {
	// Warning or errors can be collected in a slice type
	var diags diag.Diagnostics
	pco := m.(ProviderConfOutput)
	connappid := d.Get("id").(string)
	authctx := getConnectedAppAuthCtx(ctx, &pco)

	//request connected app
	res, httpr, err := pco.connectedappclient.DefaultApi.ConnectedApplicationsConnAppIdGet(authctx, connappid).Execute()
	defer httpr.Body.Close()
	if err != nil {
		var details string
		if httpr != nil {
			b, _ := ioutil.ReadAll(httpr.Body)
			details = string(b)
		} else {
			details = err.Error()
		}
		diags := append(diags, diag.Diagnostic{
			Severity: diag.Error,
			Summary:  "Unable to Get connected app",
			Detail:   details,
		})
		return diags
	}

	//process data
	connappinstance := flattenConnectedAppData(&res)

	// Is it a "on behalf of user" connected apps?
	if granttypes := connappinstance["grant_types"]; granttypes != nil && StringInSlice(granttypes.([]string), "client_credentials", true) {
		// Yes, then load the scopes using connapps/{connapp_id}/scopes
		if scopes, error := readScopesByConnectedAppId(authctx, connappid, m); error != nil {
			diags := append(diags, diag.Diagnostic{
				Severity: diag.Error,
				Summary:  "Unable to Get connected app scopes",
				Detail:   err.Error(),
			})
			return diags
		} else {
			connappinstance["scope"] = scopes
		}
	}

	//save in data source schema
	if err := setConnectedAppAttributesToResourceData(d, connappinstance); err != nil {
		diags := append(diags, diag.Diagnostic{
			Severity: diag.Error,
			Summary:  "Unable to set Connected App",
			Detail:   err.Error(),
		})
		return diags
	}

	d.SetId(connappid)

	return diags
}

func readScopesByConnectedAppId(ctx context.Context, connappid string, m interface{}) ([]interface{}, error) {
	pco := m.(ProviderConfOutput)

	authctx := getConnectedAppAuthCtx(ctx, &pco)

	res, httpr, err := pco.connectedappclient.DefaultApi.ConnectedApplicationsConnAppIdScopesGet(authctx, connappid).Execute()

	defer httpr.Body.Close()
	if err != nil {
		var details string
		if httpr != nil {
			b, _ := ioutil.ReadAll(httpr.Body)
			details = string(b)
		} else {
			details = err.Error()
		}

		return nil, errors.New(details)
	}

	//process data
	return flattenConnectedAppScopesData(&res), nil
}

/*
* Copies the given connected app instance into the given resource data
* @param d *schema.ResourceData the resource data schema
* @param connappitem map[string]interface{} the connected app instance
 */
func setConnectedAppAttributesToResourceData(d *schema.ResourceData, connappitem map[string]interface{}) error {
	attributes := getConnectedAppAttributes()
	if connappitem != nil {
		for _, attr := range attributes {
			if err := d.Set(attr, connappitem[attr]); err != nil {
				return fmt.Errorf("unable to set Connected App attribute %s\n details: %s", attr, err)
			}
		}
	}
	return nil
}

/*
* Transforms a connApp.ConnectedAppRespExt object to the dataSourceConnectedApp schema
* @param connappitem *connApp.ConnectedAppRespExt the connected app struct
* @return the connected app mapped struct
 */
func flattenConnectedAppData(connappitem *connApp.ConnectedAppRespExt) map[string]interface{} {
	if connappitem != nil {
		item := make(map[string]interface{})

		// connApp.ConnectedAppCore attributes
		item["name"] = connappitem.GetClientName()
		item["grant_types"] = connappitem.GetGrantTypes()
		item["public_keys"] = connappitem.GetPublicKeys()
		item["redirect_uris"] = connappitem.GetRedirectUris()
		item["client_uri"] = connappitem.GetClientUri()
		item["audience"] = connappitem.GetAudience()

		scopes := make([]interface{}, len(connappitem.GetScopes()))
		for j, scope := range connappitem.GetScopes() {
			s := make(map[string]interface{})

			s["scope"] = scope

			scopes[j] = s
		}
		item["scope"] = scopes

		// connApp.ConnectedAppRespExt extra attributes
		item["id"] = connappitem.GetClientId()
		item["secret"] = connappitem.GetClientSecret()
		item["organization_id"] = connappitem.GetOwnerOrgId()
		item["user_id"] = connappitem.GetOwnerUserId()
		item["enabled"] = connappitem.GetEnabled()
		item["policy_uri"] = connappitem.GetPolicyUri()
		item["tos_uri"] = connappitem.GetTosUri()
		item["cert_expiry"] = connappitem.GetCertExpiry()

		return item
	}

	return nil
}

func flattenConnectedAppScopesData(scopes *connApp.InlineResponse2001) []interface{} {
	if scopes != nil {
		scopes_list := make([]interface{}, len(scopes.GetData()))

		for j, scope := range scopes.GetData() {
			s := make(map[string]interface{})

			s["scope"] = scope.GetScope()

			if contextparams, ok := scope.GetContextParamsOk(); ok {
				if org_id, org_ok := contextparams.GetOrgOk(); org_ok {
					s["org_id"] = org_id
				}

				if env_id, env_ok := contextparams.GetEnvIdOk(); env_ok {
					s["env_id"] = env_id
				}
			}

			scopes_list[j] = s
		}

		return scopes_list
	}

	return nil
}

func getConnectedAppAttributes() []string {
	attributes := [...]string{
		"id", "name", "secret", "organization_id", "user_id", "grant_types", "redirect_uris",
		"scope", "public_keys", "client_uri", "enabled", "audience", "policy_uri", "tos_uri", "cert_expiry",
	}
	return attributes[:]
}
